# Generated by Django 4.2.29 on 2026-03-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('link_youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tom', models.CharField(max_length=10)),
                ('cifra_base64', models.TextField()),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tons', to='musicas.musica')),
            ],
        ),
    ]
