# Generated by Django 4.2.29 on 2026-03-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tom',
            name='cifra_base64',
        ),
        migrations.AddField(
            model_name='tom',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf_cifras/'),
        ),
    ]
