# Generated by Django 4.2.29 on 2026-03-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0002_remove_tom_cifra_base64_tom_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tom',
            name='pdf',
            field=models.FileField(upload_to='pdf_cifras/'),
        ),
    ]
