# Generated by Django 4.2.29 on 2026-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
