# Generated by Django 4.2.29 on 2026-03-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0002_instrumento_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='icone',
        ),
    ]
