# Generated by Django 4.2.29 on 2026-03-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EscalaMusica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='escalas.escala')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicas.musica')),
                ('tom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicas.tom')),
            ],
            options={
                'unique_together': {('escala', 'musica')},
            },
        ),
    ]
