# Generated by Django 4.2.29 on 2026-03-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrumentos', '0001_initial'),
        ('cultos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('culto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='cultos.culto')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.instrumento')),
            ],
        ),
    ]
