# Generated by Django 4.2.29 on 2026-03-11 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0003_alter_tom_pdf'),
        ('escalas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='culto',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='musico',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='escala',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EscalaMusica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='escalas.escala')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicas.musica')),
                ('tom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicas.tom')),
            ],
            options={
                'unique_together': {('escala', 'musica', 'tom')},
            },
        ),
    ]
