# Generated by Django 4.2.29 on 2026-03-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0003_remove_escala_culto_remove_escala_instrumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.DateField(),
        ),
    ]
