# Generated by Django 4.2.29 on 2026-03-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0003_alter_tom_pdf'),
        ('escalas', '0004_alter_escala_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='escalamusica',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='escalamusica',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='escalas.escala'),
        ),
        migrations.AlterUniqueTogether(
            name='escalamusica',
            unique_together={('escala', 'musica')},
        ),
        migrations.RemoveField(
            model_name='escalamusica',
            name='observacao',
        ),
    ]
